name: Prepare build environment
description: Sets up the build environment for building the SDK and/or apps

inputs:
  rust:
    description: "Whether to install Rust and it's toolchains"
    required: false
    default: "false"
  
runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: "temurin"
        java-version: "17"
    - name: Set up Gradle Cache 
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629 # v2.4.2

    - name: Update Rust
      if: "inputs.rust == 'true'"
      run: rustup toolchain install stable --profile minimal
      shell: bash
    - name: Install Rust toolchains
      if: "inputs.rust == 'true'"
      run: ./install-rust-toolchains.sh
      shell: bash
    - name: Set up Rust Cache
      if: "inputs.rust == 'true'"
      uses: Swatinem/rust-cache@6fd3edff6979b79f87531400ad694fb7f2c84b1f
      with:
        workspaces: ". -> designcompose/build/intermediates/cargoTarget"
        shared-key: "gradle-rust"
        save-if: ${{ github.ref != 'refs/heads/main' }}